name = "LibUSB"
uuid = "1afde568-c220-478b-8c78-633644781b80"
authors = ["Éric Thiébaut <eric.thiebaut@univ-lyon1.fr> and contributors"]
version = "0.1.5"

[deps]
Clang = "40e3b903-d033-50b4-a0cc-940c62c95e31"
libusb_jll = "a877fdc9-fe69-5ed6-b93d-11ecd0dc2d49"

[compat]
Clang = "≥0.14"
julia = "1.6"
libusb_jll = "1.0"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
